version: '3'

tasks:

  run:
    desc: Run local streamlit app
    cmds:
      - uv sync --locked
      - uv run streamlit run src/exposurestats/app.py

  run-docker:
    desc: Build and run docker container
    cmds:
      - uv sync --locked
      - docker compose -f docker/compose.yaml --env-file .env up --build

  run-ratings:
    desc: Run ratings tool
    cmds:
      - Echo like so: "uv run ratings ..."

  format:
    desc: Format code with ruff
    cmds:
      - uv run ruff format src/ tests/
    sources:
      - src/**/*.py
      - tests/**/*.py

  install-dev:
    desc: Install development dependencies
    cmds:
      - uv sync --group dev --locked --link-mode=copy