services:
  web:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    image: exposurestats
    container_name: exposurestats
    ports:
      - "8001:8001"
    volumes:
      - ..:/app
      - /app/.venv
    environment:
      - DEFAULT_PATH=/app/data/images
