FROM python:3.12-slim

WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

EXPOSE 8080

COPY . .

RUN pip install --no-cache-dir -U pip && \
    pip install uv && \
    uv venv .venv && \
    . .venv/bin/activate && \
    chmod +x install_tools.sh && \
    sh install_tools.sh && \
    pip install -r requirements.txt && \
    pip install -e .

ENTRYPOINT ["streamlit", "run", "src/exposurestats/app.py", "--server.port=8080", "--server.address=0.0.0.0"]