FROM python:3.13-slim-trixie
COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

WORKDIR /app

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1 \
    UV_LINK_MODE=copy



# COPY . .

# RUN pip install --no-cache-dir -U pip && \
#     pip install uv && \
#     uv venv .venv && \
#     . .venv/bin/activate && \
#     chmod +x install_tools.sh && \
#     pip install -r requirements.txt && \
#     pip install -e .


# Copy dependency files first for better caching
COPY pyproject.toml uv.lock ./

# Sync dependencies (this layer will be cached if dependencies don't change)
RUN uv sync --locked

# Copy the rest of the project
COPY . .    

EXPOSE 8001
ENTRYPOINT ["uv", "run", "streamlit", "run", "src/exposurestats/app.py", "--server.port=8001", "--server.address=0.0.0.0"]